### ISSUE TITLE
Mixing with calc causes error

### ISSUE THREAD

**Issue by andylobban** [troch/postcss-responsive-values#1]
`padding: calc(5rem + $headerHeight) responsive(whitespaceBase) 3rem;` 
outputs 
`padding: calc 1.2rem 3rem;`

Is there a workaround or does it need a fix?

**Comment by troch** [comment]
It does need a fix. Alternatively you should be able to do:

``` css
`$customVar: calc(5rem + $headerHeight);

.your_class {
    padding: $customVar responsive(whitespaceBase) 3rem;`
}
```
